remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

url: https://freedombrowser.github.io
title: Freedombrowser Repositories
description: The code behind many of our browser's utilities.
show_downloads: false
github:
  repository_url: https://github.com/freedombrowser